services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DMK\MkcacheQueue\:
        resource: '../Classes/*'

    DMK\MkcacheQueue\Command\ProcessQueueCommand:
        tags:
            - name: 'console.command'
              command: 'cache:process-queue'
              schedulable: true

    DMK\MkcacheQueue\Utility\ExtensionConfiguration:
        public: true

    DMK\MkcacheQueue\Utility\Registry:
        public: true

    DMK\MkcacheQueue\Utility\Queue:
        public: true
